apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: library/redis:latest
        name: redis
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: dbredis
      restartPolicy: Always
      volumes:
      - name: dbredis
        persistentVolumeClaim:
          claimName: dbredis
status: {}
