apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 12
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: lotrekagency/website:latest
        ports:
        - containerPort: 5000
